version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run start:dev
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb
    networks:
      - trade-app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - trade-app-network

networks:
  trade-app-network:
    driver: bridge

volumes:
  mongodb_data: 