import { KlineInterval } from 'src/bybit/dto/get-kline.dto';
import { MomentumEmaStrategyItem } from '../interfaces/momentum-ema-srategy';
import {
  Strategy,
  StrategyType,
} from 'src/strategies-handler/interfaces/strategies-handler-common.interface';

export const DEFAULT_STRATEGY_PARAMS_TEST: Strategy[] = [
  // 1 хвилина - 6 стратегій
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1m Ultra Aggressive',
      interval: KlineInterval.ONE_MINUTE,
      minAdxStrength: 15,
      minPriceChangePercent: 0.2,
      minVolatilityPercent: 0.3,
      emaShortPeriod: 3,
      emaLongPeriod: 8,
      maxAtrPercent: 2,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 30,
      minConfidence: 0.65,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1m Aggressive',
      interval: KlineInterval.ONE_MINUTE,
      minAdxStrength: 20,
      minPriceChangePercent: 0.3,
      minVolatilityPercent: 0.4,
      emaShortPeriod: 5,
      emaLongPeriod: 13,
      maxAtrPercent: 3,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 50,
      minConfidence: 0.7,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1m Moderate',
      interval: KlineInterval.ONE_MINUTE,
      minAdxStrength: 25,
      minPriceChangePercent: 0.4,
      minVolatilityPercent: 0.5,
      emaShortPeriod: 7,
      emaLongPeriod: 21,
      maxAtrPercent: 4,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 100,
      minConfidence: 0.8,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1m Conservative',
      interval: KlineInterval.ONE_MINUTE,
      minAdxStrength: 30,
      minPriceChangePercent: 0.5,
      minVolatilityPercent: 0.6,
      emaShortPeriod: 9,
      emaLongPeriod: 26,
      maxAtrPercent: 5,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 150,
      minConfidence: 0.85,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1m High Volatility',
      interval: KlineInterval.ONE_MINUTE,
      minAdxStrength: 22,
      minPriceChangePercent: 0.35,
      minVolatilityPercent: 0.7,
      emaShortPeriod: 4,
      emaLongPeriod: 10,
      maxAtrPercent: 4,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 40,
      minConfidence: 0.75,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1m Low Volatility',
      interval: KlineInterval.ONE_MINUTE,
      minAdxStrength: 28,
      minPriceChangePercent: 0.25,
      minVolatilityPercent: 0.3,
      emaShortPeriod: 8,
      emaLongPeriod: 24,
      maxAtrPercent: 2,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 120,
      minConfidence: 0.82,
    } as MomentumEmaStrategyItem,
  },

  // 3 хвилини - 6 стратегій
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 3m Ultra Aggressive',
      interval: KlineInterval.THREE_MINUTES,
      minAdxStrength: 18,
      minPriceChangePercent: 0.3,
      minVolatilityPercent: 0.4,
      emaShortPeriod: 5,
      emaLongPeriod: 15,
      maxAtrPercent: 3,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 60,
      minConfidence: 0.7,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 3m Aggressive',
      interval: KlineInterval.THREE_MINUTES,
      minAdxStrength: 22,
      minPriceChangePercent: 0.4,
      minVolatilityPercent: 0.5,
      emaShortPeriod: 7,
      emaLongPeriod: 21,
      maxAtrPercent: 4,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 75,
      minConfidence: 0.75,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 3m Moderate',
      interval: KlineInterval.THREE_MINUTES,
      minAdxStrength: 27,
      minPriceChangePercent: 0.5,
      minVolatilityPercent: 0.6,
      emaShortPeriod: 9,
      emaLongPeriod: 26,
      maxAtrPercent: 5,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 125,
      minConfidence: 0.85,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 3m Conservative',
      interval: KlineInterval.THREE_MINUTES,
      minAdxStrength: 32,
      minPriceChangePercent: 0.6,
      minVolatilityPercent: 0.7,
      emaShortPeriod: 12,
      emaLongPeriod: 30,
      maxAtrPercent: 6,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 175,
      minConfidence: 0.9,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 3m High Volatility',
      interval: KlineInterval.THREE_MINUTES,
      minAdxStrength: 24,
      minPriceChangePercent: 0.45,
      minVolatilityPercent: 0.8,
      emaShortPeriod: 6,
      emaLongPeriod: 18,
      maxAtrPercent: 5,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 65,
      minConfidence: 0.78,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 3m Low Volatility',
      interval: KlineInterval.THREE_MINUTES,
      minAdxStrength: 30,
      minPriceChangePercent: 0.35,
      minVolatilityPercent: 0.4,
      emaShortPeriod: 10,
      emaLongPeriod: 28,
      maxAtrPercent: 3,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 150,
      minConfidence: 0.88,
    } as MomentumEmaStrategyItem,
  },

  // 5 хвилин - 6 стратегій
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 5m Ultra Aggressive',
      interval: KlineInterval.FIVE_MINUTES,
      minAdxStrength: 20,
      minPriceChangePercent: 0.4,
      minVolatilityPercent: 0.5,
      emaShortPeriod: 7,
      emaLongPeriod: 20,
      maxAtrPercent: 4,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 80,
      minConfidence: 0.75,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 5m Aggressive',
      interval: KlineInterval.FIVE_MINUTES,
      minAdxStrength: 25,
      minPriceChangePercent: 0.5,
      minVolatilityPercent: 0.6,
      emaShortPeriod: 9,
      emaLongPeriod: 26,
      maxAtrPercent: 5,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 100,
      minConfidence: 0.8,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 5m Moderate',
      interval: KlineInterval.FIVE_MINUTES,
      minAdxStrength: 30,
      minPriceChangePercent: 0.6,
      minVolatilityPercent: 0.7,
      emaShortPeriod: 12,
      emaLongPeriod: 30,
      maxAtrPercent: 6,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 150,
      minConfidence: 0.85,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 5m Conservative',
      interval: KlineInterval.FIVE_MINUTES,
      minAdxStrength: 35,
      minPriceChangePercent: 0.7,
      minVolatilityPercent: 0.8,
      emaShortPeriod: 15,
      emaLongPeriod: 34,
      maxAtrPercent: 7,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 200,
      minConfidence: 0.9,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 5m High Volatility',
      interval: KlineInterval.FIVE_MINUTES,
      minAdxStrength: 26,
      minPriceChangePercent: 0.55,
      minVolatilityPercent: 0.9,
      emaShortPeriod: 8,
      emaLongPeriod: 22,
      maxAtrPercent: 6,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 90,
      minConfidence: 0.82,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 5m Low Volatility',
      interval: KlineInterval.FIVE_MINUTES,
      minAdxStrength: 32,
      minPriceChangePercent: 0.45,
      minVolatilityPercent: 0.5,
      emaShortPeriod: 13,
      emaLongPeriod: 32,
      maxAtrPercent: 4,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 170,
      minConfidence: 0.88,
    } as MomentumEmaStrategyItem,
  },

  // 15 хвилин - 6 стратегій
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 15m Ultra Aggressive',
      interval: KlineInterval.FIFTEEN_MINUTES,
      minAdxStrength: 24,
      minPriceChangePercent: 0.5,
      minVolatilityPercent: 0.6,
      emaShortPeriod: 10,
      emaLongPeriod: 25,
      maxAtrPercent: 5,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 100,
      minConfidence: 0.8,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 15m Aggressive',
      interval: KlineInterval.FIFTEEN_MINUTES,
      minAdxStrength: 28,
      minPriceChangePercent: 0.6,
      minVolatilityPercent: 0.7,
      emaShortPeriod: 12,
      emaLongPeriod: 30,
      maxAtrPercent: 6,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 125,
      minConfidence: 0.85,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 15m Moderate',
      interval: KlineInterval.FIFTEEN_MINUTES,
      minAdxStrength: 33,
      minPriceChangePercent: 0.7,
      minVolatilityPercent: 0.8,
      emaShortPeriod: 15,
      emaLongPeriod: 34,
      maxAtrPercent: 7,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 175,
      minConfidence: 0.9,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 15m Conservative',
      interval: KlineInterval.FIFTEEN_MINUTES,
      minAdxStrength: 38,
      minPriceChangePercent: 0.8,
      minVolatilityPercent: 0.9,
      emaShortPeriod: 18,
      emaLongPeriod: 40,
      maxAtrPercent: 8,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 225,
      minConfidence: 0.95,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 15m High Volatility',
      interval: KlineInterval.FIFTEEN_MINUTES,
      minAdxStrength: 30,
      minPriceChangePercent: 0.65,
      minVolatilityPercent: 1.0,
      emaShortPeriod: 11,
      emaLongPeriod: 27,
      maxAtrPercent: 7,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 110,
      minConfidence: 0.87,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 15m Low Volatility',
      interval: KlineInterval.FIFTEEN_MINUTES,
      minAdxStrength: 36,
      minPriceChangePercent: 0.55,
      minVolatilityPercent: 0.6,
      emaShortPeriod: 16,
      emaLongPeriod: 36,
      maxAtrPercent: 5,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 190,
      minConfidence: 0.92,
    } as MomentumEmaStrategyItem,
  },

  // 30 хвилин - 6 стратегій
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 30m Ultra Aggressive',
      interval: KlineInterval.THIRTY_MINUTES,
      minAdxStrength: 26,
      minPriceChangePercent: 0.6,
      minVolatilityPercent: 0.7,
      emaShortPeriod: 13,
      emaLongPeriod: 30,
      maxAtrPercent: 6,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 125,
      minConfidence: 0.85,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 30m Aggressive',
      interval: KlineInterval.THIRTY_MINUTES,
      minAdxStrength: 30,
      minPriceChangePercent: 0.7,
      minVolatilityPercent: 0.8,
      emaShortPeriod: 15,
      emaLongPeriod: 34,
      maxAtrPercent: 7,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 150,
      minConfidence: 0.9,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 30m Moderate',
      interval: KlineInterval.THIRTY_MINUTES,
      minAdxStrength: 35,
      minPriceChangePercent: 0.8,
      minVolatilityPercent: 0.9,
      emaShortPeriod: 18,
      emaLongPeriod: 40,
      maxAtrPercent: 8,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 200,
      minConfidence: 0.95,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 30m Conservative',
      interval: KlineInterval.THIRTY_MINUTES,
      minAdxStrength: 40,
      minPriceChangePercent: 0.9,
      minVolatilityPercent: 1.0,
      emaShortPeriod: 21,
      emaLongPeriod: 45,
      maxAtrPercent: 9,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 250,
      minConfidence: 0.98,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 30m High Volatility',
      interval: KlineInterval.THIRTY_MINUTES,
      minAdxStrength: 32,
      minPriceChangePercent: 0.75,
      minVolatilityPercent: 1.1,
      emaShortPeriod: 14,
      emaLongPeriod: 32,
      maxAtrPercent: 8,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 135,
      minConfidence: 0.92,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 30m Low Volatility',
      interval: KlineInterval.THIRTY_MINUTES,
      minAdxStrength: 38,
      minPriceChangePercent: 0.65,
      minVolatilityPercent: 0.7,
      emaShortPeriod: 19,
      emaLongPeriod: 42,
      maxAtrPercent: 6,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 210,
      minConfidence: 0.96,
    } as MomentumEmaStrategyItem,
  },

  // 1 година - 6 стратегій
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1h Ultra Aggressive',
      interval: KlineInterval.ONE_HOUR,
      minAdxStrength: 28,
      minPriceChangePercent: 0.7,
      minVolatilityPercent: 0.8,
      emaShortPeriod: 16,
      emaLongPeriod: 35,
      maxAtrPercent: 7,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 150,
      minConfidence: 0.9,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1h Aggressive',
      interval: KlineInterval.ONE_HOUR,
      minAdxStrength: 32,
      minPriceChangePercent: 0.8,
      minVolatilityPercent: 0.9,
      emaShortPeriod: 18,
      emaLongPeriod: 40,
      maxAtrPercent: 8,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 175,
      minConfidence: 0.95,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1h Moderate',
      interval: KlineInterval.ONE_HOUR,
      minAdxStrength: 37,
      minPriceChangePercent: 0.9,
      minVolatilityPercent: 1.0,
      emaShortPeriod: 21,
      emaLongPeriod: 45,
      maxAtrPercent: 9,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 225,
      minConfidence: 0.98,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1h Conservative',
      interval: KlineInterval.ONE_HOUR,
      minAdxStrength: 42,
      minPriceChangePercent: 1.0,
      minVolatilityPercent: 1.1,
      emaShortPeriod: 24,
      emaLongPeriod: 50,
      maxAtrPercent: 10,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 275,
      minConfidence: 0.99,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1h High Volatility',
      interval: KlineInterval.ONE_HOUR,
      minAdxStrength: 34,
      minPriceChangePercent: 0.85,
      minVolatilityPercent: 1.2,
      emaShortPeriod: 17,
      emaLongPeriod: 37,
      maxAtrPercent: 9,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 160,
      minConfidence: 0.96,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1h Low Volatility',
      interval: KlineInterval.ONE_HOUR,
      minAdxStrength: 40,
      minPriceChangePercent: 0.75,
      minVolatilityPercent: 0.8,
      emaShortPeriod: 22,
      emaLongPeriod: 47,
      maxAtrPercent: 7,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 240,
      minConfidence: 0.985,
    } as MomentumEmaStrategyItem,
  },

  // 2 години - 6 стратегій
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 2h Ultra Aggressive',
      interval: KlineInterval.TWO_HOURS,
      minAdxStrength: 30,
      minPriceChangePercent: 0.8,
      minVolatilityPercent: 0.9,
      emaShortPeriod: 19,
      emaLongPeriod: 40,
      maxAtrPercent: 8,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 175,
      minConfidence: 0.95,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 2h Aggressive',
      interval: KlineInterval.TWO_HOURS,
      minAdxStrength: 34,
      minPriceChangePercent: 0.9,
      minVolatilityPercent: 1.0,
      emaShortPeriod: 21,
      emaLongPeriod: 45,
      maxAtrPercent: 9,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 200,
      minConfidence: 0.98,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 2h Moderate',
      interval: KlineInterval.TWO_HOURS,
      minAdxStrength: 39,
      minPriceChangePercent: 1.0,
      minVolatilityPercent: 1.1,
      emaShortPeriod: 24,
      emaLongPeriod: 50,
      maxAtrPercent: 10,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 250,
      minConfidence: 0.99,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 2h Conservative',
      interval: KlineInterval.TWO_HOURS,
      minAdxStrength: 44,
      minPriceChangePercent: 1.1,
      minVolatilityPercent: 1.2,
      emaShortPeriod: 27,
      emaLongPeriod: 55,
      maxAtrPercent: 11,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 300,
      minConfidence: 0.995,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 2h High Volatility',
      interval: KlineInterval.TWO_HOURS,
      minAdxStrength: 36,
      minPriceChangePercent: 0.95,
      minVolatilityPercent: 1.3,
      emaShortPeriod: 20,
      emaLongPeriod: 42,
      maxAtrPercent: 10,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 185,
      minConfidence: 0.97,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 2h Low Volatility',
      interval: KlineInterval.TWO_HOURS,
      minAdxStrength: 42,
      minPriceChangePercent: 0.85,
      minVolatilityPercent: 0.9,
      emaShortPeriod: 25,
      emaLongPeriod: 52,
      maxAtrPercent: 8,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 265,
      minConfidence: 0.99,
    } as MomentumEmaStrategyItem,
  },

  // 4 години - 6 стратегій
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 4h Ultra Aggressive',
      interval: KlineInterval.FOUR_HOURS,
      minAdxStrength: 32,
      minPriceChangePercent: 0.9,
      minVolatilityPercent: 1.0,
      emaShortPeriod: 22,
      emaLongPeriod: 45,
      maxAtrPercent: 9,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 200,
      minConfidence: 0.98,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 4h Aggressive',
      interval: KlineInterval.FOUR_HOURS,
      minAdxStrength: 36,
      minPriceChangePercent: 1.0,
      minVolatilityPercent: 1.1,
      emaShortPeriod: 24,
      emaLongPeriod: 50,
      maxAtrPercent: 10,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 225,
      minConfidence: 0.99,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 4h Moderate',
      interval: KlineInterval.FOUR_HOURS,
      minAdxStrength: 41,
      minPriceChangePercent: 1.1,
      minVolatilityPercent: 1.2,
      emaShortPeriod: 27,
      emaLongPeriod: 55,
      maxAtrPercent: 11,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 275,
      minConfidence: 0.995,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 4h Conservative',
      interval: KlineInterval.FOUR_HOURS,
      minAdxStrength: 46,
      minPriceChangePercent: 1.2,
      minVolatilityPercent: 1.3,
      emaShortPeriod: 30,
      emaLongPeriod: 60,
      maxAtrPercent: 12,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 325,
      minConfidence: 0.998,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 4h High Volatility',
      interval: KlineInterval.FOUR_HOURS,
      minAdxStrength: 38,
      minPriceChangePercent: 1.05,
      minVolatilityPercent: 1.4,
      emaShortPeriod: 23,
      emaLongPeriod: 47,
      maxAtrPercent: 11,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 210,
      minConfidence: 0.985,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 4h Low Volatility',
      interval: KlineInterval.FOUR_HOURS,
      minAdxStrength: 44,
      minPriceChangePercent: 0.95,
      minVolatilityPercent: 1.0,
      emaShortPeriod: 28,
      emaLongPeriod: 57,
      maxAtrPercent: 9,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 290,
      minConfidence: 0.995,
    } as MomentumEmaStrategyItem,
  },

  // 6 годин - 6 стратегій
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 6h Ultra Aggressive',
      interval: KlineInterval.SIX_HOURS,
      minAdxStrength: 34,
      minPriceChangePercent: 1.0,
      minVolatilityPercent: 1.1,
      emaShortPeriod: 25,
      emaLongPeriod: 50,
      maxAtrPercent: 10,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 225,
      minConfidence: 0.99,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 6h Aggressive',
      interval: KlineInterval.SIX_HOURS,
      minAdxStrength: 38,
      minPriceChangePercent: 1.1,
      minVolatilityPercent: 1.2,
      emaShortPeriod: 27,
      emaLongPeriod: 55,
      maxAtrPercent: 11,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 250,
      minConfidence: 0.995,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 6h Moderate',
      interval: KlineInterval.SIX_HOURS,
      minAdxStrength: 43,
      minPriceChangePercent: 1.2,
      minVolatilityPercent: 1.3,
      emaShortPeriod: 30,
      emaLongPeriod: 60,
      maxAtrPercent: 12,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 300,
      minConfidence: 0.998,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 6h Conservative',
      interval: KlineInterval.SIX_HOURS,
      minAdxStrength: 48,
      minPriceChangePercent: 1.3,
      minVolatilityPercent: 1.4,
      emaShortPeriod: 33,
      emaLongPeriod: 65,
      maxAtrPercent: 13,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 350,
      minConfidence: 0.999,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 6h High Volatility',
      interval: KlineInterval.SIX_HOURS,
      minAdxStrength: 40,
      minPriceChangePercent: 1.15,
      minVolatilityPercent: 1.5,
      emaShortPeriod: 26,
      emaLongPeriod: 52,
      maxAtrPercent: 12,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 235,
      minConfidence: 0.992,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 6h Low Volatility',
      interval: KlineInterval.SIX_HOURS,
      minAdxStrength: 46,
      minPriceChangePercent: 1.05,
      minVolatilityPercent: 1.1,
      emaShortPeriod: 31,
      emaLongPeriod: 62,
      maxAtrPercent: 10,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 315,
      minConfidence: 0.998,
    } as MomentumEmaStrategyItem,
  },

  // 12 годин - 6 стратегій
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 12h Ultra Aggressive',
      interval: KlineInterval.TWELVE_HOURS,
      minAdxStrength: 36,
      minPriceChangePercent: 1.1,
      minVolatilityPercent: 1.2,
      emaShortPeriod: 28,
      emaLongPeriod: 55,
      maxAtrPercent: 11,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 250,
      minConfidence: 0.995,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 12h Aggressive',
      interval: KlineInterval.TWELVE_HOURS,
      minAdxStrength: 40,
      minPriceChangePercent: 1.2,
      minVolatilityPercent: 1.3,
      emaShortPeriod: 30,
      emaLongPeriod: 60,
      maxAtrPercent: 12,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 275,
      minConfidence: 0.998,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 12h Moderate',
      interval: KlineInterval.TWELVE_HOURS,
      minAdxStrength: 45,
      minPriceChangePercent: 1.3,
      minVolatilityPercent: 1.4,
      emaShortPeriod: 33,
      emaLongPeriod: 65,
      maxAtrPercent: 13,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 325,
      minConfidence: 0.999,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 12h Conservative',
      interval: KlineInterval.TWELVE_HOURS,
      minAdxStrength: 50,
      minPriceChangePercent: 1.4,
      minVolatilityPercent: 1.5,
      emaShortPeriod: 36,
      emaLongPeriod: 70,
      maxAtrPercent: 14,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 375,
      minConfidence: 0.9995,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 12h High Volatility',
      interval: KlineInterval.TWELVE_HOURS,
      minAdxStrength: 42,
      minPriceChangePercent: 1.25,
      minVolatilityPercent: 1.6,
      emaShortPeriod: 29,
      emaLongPeriod: 57,
      maxAtrPercent: 13,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 260,
      minConfidence: 0.996,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 12h Low Volatility',
      interval: KlineInterval.TWELVE_HOURS,
      minAdxStrength: 48,
      minPriceChangePercent: 1.15,
      minVolatilityPercent: 1.2,
      emaShortPeriod: 34,
      emaLongPeriod: 67,
      maxAtrPercent: 11,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 340,
      minConfidence: 0.999,
    } as MomentumEmaStrategyItem,
  },

  // 1 день - 6 стратегій
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1d Ultra Aggressive',
      interval: KlineInterval.ONE_DAY,
      minAdxStrength: 38,
      minPriceChangePercent: 1.2,
      minVolatilityPercent: 1.3,
      emaShortPeriod: 31,
      emaLongPeriod: 60,
      maxAtrPercent: 12,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 275,
      minConfidence: 0.998,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1d Aggressive',
      interval: KlineInterval.ONE_DAY,
      minAdxStrength: 42,
      minPriceChangePercent: 1.3,
      minVolatilityPercent: 1.4,
      emaShortPeriod: 33,
      emaLongPeriod: 65,
      maxAtrPercent: 13,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 300,
      minConfidence: 0.999,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1d Moderate',
      interval: KlineInterval.ONE_DAY,
      minAdxStrength: 47,
      minPriceChangePercent: 1.4,
      minVolatilityPercent: 1.5,
      emaShortPeriod: 36,
      emaLongPeriod: 70,
      maxAtrPercent: 14,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 350,
      minConfidence: 0.9995,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1d Conservative',
      interval: KlineInterval.ONE_DAY,
      minAdxStrength: 52,
      minPriceChangePercent: 1.5,
      minVolatilityPercent: 1.6,
      emaShortPeriod: 39,
      emaLongPeriod: 75,
      maxAtrPercent: 15,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 400,
      minConfidence: 0.9998,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1d High Volatility',
      interval: KlineInterval.ONE_DAY,
      minAdxStrength: 44,
      minPriceChangePercent: 1.35,
      minVolatilityPercent: 1.7,
      emaShortPeriod: 32,
      emaLongPeriod: 62,
      maxAtrPercent: 14,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 285,
      minConfidence: 0.998,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1d Low Volatility',
      interval: KlineInterval.ONE_DAY,
      minAdxStrength: 50,
      minPriceChangePercent: 1.25,
      minVolatilityPercent: 1.3,
      emaShortPeriod: 37,
      emaLongPeriod: 72,
      maxAtrPercent: 12,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 365,
      minConfidence: 0.9995,
    } as MomentumEmaStrategyItem,
  },

  // 1 тиждень - 6 стратегій
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1w Ultra Aggressive',
      interval: KlineInterval.ONE_WEEK,
      minAdxStrength: 40,
      minPriceChangePercent: 1.3,
      minVolatilityPercent: 1.4,
      emaShortPeriod: 34,
      emaLongPeriod: 65,
      maxAtrPercent: 13,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 300,
      minConfidence: 0.999,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1w Aggressive',
      interval: KlineInterval.ONE_WEEK,
      minAdxStrength: 44,
      minPriceChangePercent: 1.4,
      minVolatilityPercent: 1.5,
      emaShortPeriod: 36,
      emaLongPeriod: 70,
      maxAtrPercent: 14,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 325,
      minConfidence: 0.9995,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1w Moderate',
      interval: KlineInterval.ONE_WEEK,
      minAdxStrength: 49,
      minPriceChangePercent: 1.5,
      minVolatilityPercent: 1.6,
      emaShortPeriod: 39,
      emaLongPeriod: 75,
      maxAtrPercent: 15,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 375,
      minConfidence: 0.9998,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1w Conservative',
      interval: KlineInterval.ONE_WEEK,
      minAdxStrength: 54,
      minPriceChangePercent: 1.6,
      minVolatilityPercent: 1.7,
      emaShortPeriod: 42,
      emaLongPeriod: 80,
      maxAtrPercent: 16,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 425,
      minConfidence: 0.9999,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1w High Volatility',
      interval: KlineInterval.ONE_WEEK,
      minAdxStrength: 46,
      minPriceChangePercent: 1.45,
      minVolatilityPercent: 1.8,
      emaShortPeriod: 35,
      emaLongPeriod: 67,
      maxAtrPercent: 15,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 310,
      minConfidence: 0.999,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1w Low Volatility',
      interval: KlineInterval.ONE_WEEK,
      minAdxStrength: 52,
      minPriceChangePercent: 1.35,
      minVolatilityPercent: 1.4,
      emaShortPeriod: 40,
      emaLongPeriod: 77,
      maxAtrPercent: 13,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 390,
      minConfidence: 0.9998,
    } as MomentumEmaStrategyItem,
  },

  // 1 місяць - 6 стратегій
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1M Ultra Aggressive',
      interval: KlineInterval.ONE_MONTH,
      minAdxStrength: 42,
      minPriceChangePercent: 1.4,
      minVolatilityPercent: 1.5,
      emaShortPeriod: 37,
      emaLongPeriod: 70,
      maxAtrPercent: 14,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 325,
      minConfidence: 0.9995,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1M Aggressive',
      interval: KlineInterval.ONE_MONTH,
      minAdxStrength: 46,
      minPriceChangePercent: 1.5,
      minVolatilityPercent: 1.6,
      emaShortPeriod: 39,
      emaLongPeriod: 75,
      maxAtrPercent: 15,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 350,
      minConfidence: 0.9998,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1M Moderate',
      interval: KlineInterval.ONE_MONTH,
      minAdxStrength: 51,
      minPriceChangePercent: 1.6,
      minVolatilityPercent: 1.7,
      emaShortPeriod: 42,
      emaLongPeriod: 80,
      maxAtrPercent: 16,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 400,
      minConfidence: 0.9999,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1M Conservative',
      interval: KlineInterval.ONE_MONTH,
      minAdxStrength: 56,
      minPriceChangePercent: 1.7,
      minVolatilityPercent: 1.8,
      emaShortPeriod: 45,
      emaLongPeriod: 85,
      maxAtrPercent: 17,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 450,
      minConfidence: 0.99995,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1M High Volatility',
      interval: KlineInterval.ONE_MONTH,
      minAdxStrength: 48,
      minPriceChangePercent: 1.55,
      minVolatilityPercent: 1.9,
      emaShortPeriod: 38,
      emaLongPeriod: 72,
      maxAtrPercent: 16,
      trendOnly: false,
      dynamicAtrFilter: true,
      limit: 335,
      minConfidence: 0.9995,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1M Low Volatility',
      interval: KlineInterval.ONE_MONTH,
      minAdxStrength: 54,
      minPriceChangePercent: 1.45,
      minVolatilityPercent: 1.5,
      emaShortPeriod: 43,
      emaLongPeriod: 82,
      maxAtrPercent: 14,
      trendOnly: true,
      dynamicAtrFilter: true,
      limit: 415,
      minConfidence: 0.9999,
    } as MomentumEmaStrategyItem,
  },
];
