import { KlineCategory, KlineInterval } from 'src/bybit/dto/get-kline.dto';
import { MomentumEmaStrategyItem } from '../interfaces/momentum-ema-srategy';
import {
  Strategy,
  StrategyType,
} from 'src/strategies-handler/interfaces/strategies-handler-common.interface';

export const DEFAULT_CONFIDENCE_VALUE = 0.65;
export const DEFAULT_CATEGORY = KlineCategory.LINEAR;
export const DEFAULT_STRATEGY_PARAMS_TEST: Strategy[] = [
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 1',
      interval: KlineInterval.ONE_MINUTE,
      minAdxStrength: 15,
      minPriceChangePercent: 0.4,
      minVolatilityPercent: 0.5,
      emaShortPeriod: 5,
      emaLongPeriod: 13,
      maxAtrPercent: 4,
      trendOnly: false,
      dynamicAtrFilter: false,
      limit: 100,
      minConfidence: 0.75,
      // category: DEFAULT_CATEGORY,
    } as MomentumEmaStrategyItem,
  },
  {
    strategyType: StrategyType.MOMENTUM_EMA_CROSS,
    params: {
      name: 'Momentum EMA Cross 2',
      interval: KlineInterval.THREE_MINUTES,
      minAdxStrength: 15,
      minPriceChangePercent: 0.4,
      minVolatilityPercent: 0.5,
      emaShortPeriod: 5,
      emaLongPeriod: 13,
      maxAtrPercent: 4,
      trendOnly: false,
      dynamicAtrFilter: false,
      limit: 100,
      minConfidence: 0.75,
      // category: DEFAULT_CATEGORY,
    } as MomentumEmaStrategyItem,
  },
];

// export const DEFAULT_STRATEGY_PARAMS = [
//   {
//     interval: '1',
//     configs: [
//       {
//         emaShortPeriod: 5,
//         emaLongPeriod: 13,
//         minPriceChangePercent: 0.4,
//         minAdxStrength: 15,
//         minVolatilityPercent: 0.5,
//         maxAtrPercent: 4,
//         trendOnly: false,
//         dynamicAtrFilter: false,
//         confidenceValue: 0.65,
//         limit: 100,
//       },
//       {
//         emaShortPeriod: 9,
//         emaLongPeriod: 21,
//         minPriceChangePercent: 0.6,
//         minAdxStrength: 20,
//         minVolatilityPercent: 0.7,
//         maxAtrPercent: 5,
//         trendOnly: true,
//         dynamicAtrFilter: true,
//         confidenceValue: 0.7,
//         limit: 200,
//       },
//     ],
//   },
//   {
//     interval: '3',
//     configs: [
//       {
//         emaShortPeriod: 7,
//         emaLongPeriod: 20,
//         minPriceChangePercent: 0.5,
//         minAdxStrength: 18,
//         minVolatilityPercent: 0.6,
//         maxAtrPercent: 5,
//         trendOnly: true,
//         dynamicAtrFilter: false,
//         confidenceValue: 0.7,
//         limit: 150,
//       },
//     ],
//   },
//   {
//     interval: '5',
//     configs: [
//       {
//         emaShortPeriod: 7,
//         emaLongPeriod: 21,
//         minPriceChangePercent: 0.7,
//         minAdxStrength: 22,
//         minVolatilityPercent: 0.7,
//         maxAtrPercent: 5,
//         trendOnly: true,
//         dynamicAtrFilter: true,
//         confidenceValue: 0.75,
//         limit: 200,
//       },
//       {
//         emaShortPeriod: 10,
//         emaLongPeriod: 26,
//         minPriceChangePercent: 0.8,
//         minAdxStrength: 25,
//         minVolatilityPercent: 1.0,
//         maxAtrPercent: 6,
//         trendOnly: true,
//         dynamicAtrFilter: true,
//         confidenceValue: 0.8,
//         limit: 250,
//       },
//     ],
//   },
//   {
//     interval: '15',
//     configs: [
//       {
//         emaShortPeriod: 9,
//         emaLongPeriod: 21,
//         minPriceChangePercent: 1.0,
//         minAdxStrength: 25,
//         minVolatilityPercent: 1.0,
//         maxAtrPercent: 5,
//         trendOnly: true,
//         dynamicAtrFilter: true,
//         confidenceValue: 0.8,
//         limit: 200,
//       },
//       {
//         emaShortPeriod: 10,
//         emaLongPeriod: 30,
//         minPriceChangePercent: 1.2,
//         minAdxStrength: 27,
//         minVolatilityPercent: 1.2,
//         maxAtrPercent: 5,
//         trendOnly: true,
//         dynamicAtrFilter: false,
//         confidenceValue: 0.85,
//         limit: 250,
//       },
//     ],
//   },
//   {
//     interval: '30',
//     configs: [
//       {
//         emaShortPeriod: 10,
//         emaLongPeriod: 26,
//         minPriceChangePercent: 1.2,
//         minAdxStrength: 25,
//         minVolatilityPercent: 1.1,
//         maxAtrPercent: 5,
//         trendOnly: true,
//         dynamicAtrFilter: true,
//         confidenceValue: 0.85,
//         limit: 200,
//       },
//     ],
//   },
//   {
//     interval: '60',
//     configs: [
//       {
//         emaShortPeriod: 12,
//         emaLongPeriod: 30,
//         minPriceChangePercent: 1.5,
//         minAdxStrength: 27,
//         minVolatilityPercent: 1.3,
//         maxAtrPercent: 5,
//         trendOnly: true,
//         dynamicAtrFilter: true,
//         confidenceValue: 0.85,
//         limit: 200,
//       },
//     ],
//   },
//   {
//     interval: '120',
//     configs: [
//       {
//         emaShortPeriod: 12,
//         emaLongPeriod: 34,
//         minPriceChangePercent: 1.8,
//         minAdxStrength: 28,
//         minVolatilityPercent: 1.5,
//         maxAtrPercent: 6,
//         trendOnly: true,
//         dynamicAtrFilter: true,
//         confidenceValue: 0.85,
//         limit: 250,
//       },
//     ],
//   },
//   {
//     interval: '240',
//     configs: [
//       {
//         emaShortPeriod: 14,
//         emaLongPeriod: 40,
//         minPriceChangePercent: 2.0,
//         minAdxStrength: 30,
//         minVolatilityPercent: 1.7,
//         maxAtrPercent: 6,
//         trendOnly: true,
//         dynamicAtrFilter: true,
//         confidenceValue: 0.88,
//         limit: 250,
//       },
//     ],
//   },
//   {
//     interval: '360',
//     configs: [
//       {
//         emaShortPeriod: 15,
//         emaLongPeriod: 45,
//         minPriceChangePercent: 2.2,
//         minAdxStrength: 30,
//         minVolatilityPercent: 1.8,
//         maxAtrPercent: 6,
//         trendOnly: true,
//         dynamicAtrFilter: true,
//         confidenceValue: 0.9,
//         limit: 300,
//       },
//     ],
//   },
//   {
//     interval: '720',
//     configs: [
//       {
//         emaShortPeriod: 18,
//         emaLongPeriod: 50,
//         minPriceChangePercent: 2.5,
//         minAdxStrength: 32,
//         minVolatilityPercent: 2.0,
//         maxAtrPercent: 6,
//         trendOnly: true,
//         dynamicAtrFilter: true,
//         confidenceValue: 0.92,
//         limit: 300,
//       },
//     ],
//   },
//   {
//     interval: 'D',
//     configs: [
//       {
//         emaShortPeriod: 20,
//         emaLongPeriod: 55,
//         minPriceChangePercent: 3.0,
//         minAdxStrength: 35,
//         minVolatilityPercent: 2.5,
//         maxAtrPercent: 7,
//         trendOnly: true,
//         dynamicAtrFilter: true,
//         confidenceValue: 0.95,
//         limit: 300,
//       },
//       {
//         emaShortPeriod: 21,
//         emaLongPeriod: 60,
//         minPriceChangePercent: 3.5,
//         minAdxStrength: 38,
//         minVolatilityPercent: 3.0,
//         maxAtrPercent: 7,
//         trendOnly: true,
//         dynamicAtrFilter: true,
//         confidenceValue: 0.95,
//         limit: 350,
//       },
//     ],
//   },
//   {
//     interval: 'W',
//     configs: [
//       {
//         emaShortPeriod: 30,
//         emaLongPeriod: 70,
//         minPriceChangePercent: 4.0,
//         minAdxStrength: 40,
//         minVolatilityPercent: 3.5,
//         maxAtrPercent: 7,
//         trendOnly: true,
//         dynamicAtrFilter: true,
//         confidenceValue: 0.97,
//         limit: 400,
//       },
//     ],
//   },
//   {
//     interval: 'M',
//     configs: [
//       {
//         emaShortPeriod: 40,
//         emaLongPeriod: 100,
//         minPriceChangePercent: 5.0,
//         minAdxStrength: 45,
//         minVolatilityPercent: 4.0,
//         maxAtrPercent: 8,
//         trendOnly: true,
//         dynamicAtrFilter: true,
//         confidenceValue: 0.98,
//         limit: 500,
//       },
//     ],
//   },
// ];
